name = "spinogambinocasino-game-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino-game.net"
HMAC_KEY = "f13c21d9770d24830860781ae39a7bb6f0a3e445b53a3e28eec8d6b38eae93f7"
COOKIE_NAME = "h3l"
PLAY_PATH = "play-now"
BUTTON_ID = "p7b11871bea95a0eeb7551adfda01ba24"
GATE_SALT = "81e53f667dd9067a"
